// src/lib/carMakes.ts
export const carMakes = [
    { label: 'Select Make', value: '' },
    { label: 'Acura', value: 'acura' },
    { label: 'Alfa Romeo', value: 'alfa-romeo' },
    { label: 'AM General', value: 'am-general' },
    { label: 'Aston Martin', value: 'aston-martin' },
    { label: 'Audi', value: 'audi' },
    { label: 'Bentley', value: 'bentley' },
    { label: 'BMW', value: 'bmw' },
    { label: 'Bugatti', value: 'bugatti' },
    { label: 'Buick', value: 'buick' },
    { label: 'Cadillac', value: 'cadillac' },
    { label: 'Chevrolet', value: 'chevrolet' },
    { label: 'Chrysler', value: 'chrysler' },
    { label: 'Daewoo', value: 'daewoo' },
    { label: 'Dodge', value: 'dodge' },
    { label: 'Eagle', value: 'eagle' },
    { label: 'Ferrari', value: 'ferrari' },
    { label: 'FIAT', value: 'fiat' },
    { label: 'Fisker', value: 'fisker' },
    { label: 'Ford', value: 'ford' },
    { label: 'Genesis', value: 'genesis' },
    { label: 'Geo', value: 'geo' },
    { label: 'GMC', value: 'gmc' },
    { label: 'Honda', value: 'honda' },
    { label: 'HUMMER', value: 'hummer' },
    { label: 'Hyundai', value: 'hyundai' },
    { label: 'INEOS', value: 'ineos' },
    { label: 'INFINITI', value: 'infiniti' },
    { label: 'Isuzu', value: 'isuzu' },
    { label: 'Jaguar', value: 'jaguar' },
    { label: 'Jeep', value: 'jeep' },
    { label: 'Karma', value: 'karma' },
    { label: 'Kia', value: 'kia' },
    { label: 'Lamborghini', value: 'lamborghini' },
    { label: 'Land Rover', value: 'land-rover' },
    { label: 'Lexus', value: 'lexus' },
    { label: 'Lincoln', value: 'lincoln' },
    { label: 'Lotus', value: 'lotus' },
    { label: 'Lucid', value: 'lucid' },
    { label: 'Maserati', value: 'maserati' },
    { label: 'Maybach', value: 'maybach' },
    { label: 'Mazda', value: 'mazda' },
    { label: 'McLaren', value: 'mclaren' },
    { label: 'Mercedes-Benz', value: 'mercedes-benz' },
    { label: 'Mercury', value: 'mercury' },
    { label: 'MINI', value: 'mini' },
    { label: 'Mitsubishi', value: 'mitsubishi' },
    { label: 'Nissan', value: 'nissan' },
    { label: 'Oldsmobile', value: 'oldsmobile' },
    { label: 'Panoz', value: 'panoz' },
    { label: 'Plymouth', value: 'plymouth' },
    { label: 'Polestar', value: 'polestar' },
    { label: 'Pontiac', value: 'pontiac' },
    { label: 'Porsche', value: 'porsche' },
    { label: 'Ram', value: 'ram' },
    { label: 'Rivian', value: 'rivian' },
    { label: 'Rolls-Royce', value: 'rolls-royce' },
    { label: 'Saab', value: 'saab' },
    { label: 'Saturn', value: 'saturn' },
    { label: 'Scion', value: 'scion' },
    { label: 'smart', value: 'smart' },
    { label: 'Spyker', value: 'spyker' },
    { label: 'Subaru', value: 'subaru' },
    { label: 'Suzuki', value: 'suzuki' },
    { label: 'Tesla', value: 'tesla' },
    { label: 'Toyota', value: 'toyota' },
    { label: 'VinFast', value: 'vinfast' },
    { label: 'Volkswagen', value: 'volkswagen' },
    { label: 'Volvo', value: 'volvo' },
  ];